name: CI/CD Pipeline #Nombre del workflow
on: #Define donde se ejecutara el workflow
	push: #Se ejecutara el workflow cuando se haga un push a la rama 'main'
		branches:
			- main
	pull_request: #Se ejecutara el workflow cuando se cree o actualice un pull request hacia la rama 'main'
		branches:
			- main

jobs: #Conjunto de pasos que se ejecutaran como parte del workflow
	build: #Nombre del job
		runs-on: ubuntu-latest #El job se ejecutara en una maquina virtual con la ultima version disponible de ubuntu
		
		steps: #Define las acciones o comandos especificos que se ejecutaran dentro del job 'Build'
			- name: Checkout code #Nombre del paso
			  uses: actions/checkout@v2 #Utiliza la accion actions/checkout@v2 para clonar el repositorio en la maquina virtual
			  
			- name: Set up Node.js #Nombre del paso
			  uses: actions/setup-node@v2 #Utiliza la accion actions/Checkout@v2 para instalar Node.js
			  with: #Se utiliza para deifinir parametros de acción
			  	node-version:'20' #Se instalara la version 20 de Node.js
			
			- name: Install dependencies #Nombre del paso
			  run: npm install #Ejecuta el comando 'npm install' para instalar las dependencias del proyecto definidas en 'package.json'
			  
			- name: Run tests #Nombre del paso
			  run: npm test #Ejecuta el comando 'npm test' para correr las pruebas definidas en el proyecto

			- name: Build Docker image #Nombre del paso
			  run: docker build -t devops-practice . #Construye la imagen de Docker utilizando el comando `docker build`
			
			- name: Run Docker container #Nombre del paso
			  run: docker run -d -p 3000:3000 devops-practice #Ejecuta el contenedor Docker en segundo plano mapeando el puerto 3000 del contenedor al puerto 3000 de la maquina virtual 